#!/bin/sh

set -e

if [ ! -d /usr/share/lider-server ]; then

    mkdir -p /usr/share/lider-server
    cp -rf /tmp/lider-server/* /usr/share/lider-server
fi

systemctl enable lider.service
systemctl start  lider.service

