#!/bin/sh

set -e

if [ -d /usr/share/lider-server ] && [ "$1" = "purge" ];then

	systemctl stop lider.service
	rm -rf /usr/share/lider-server
#    rm /etc/systemd/system/lider.service
#    rm /etc/init.d/lider
fi
